vich_uploader:
    db_driver: orm


    mappings:
        item_image:
            uri_prefix: /images/items
            upload_destination: '%kernel.project_dir%/public/images/items'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
